title: CSDMS Ivy
logo: /assets/csdms-simple.png
description: |
  Course material on scientific software development for researchers in earth
  and planetary surface processes.
theme: jekyll-theme-minimal
